[build]
  publish = "."
  functions = "netlify/functions"
  command = ""

[[redirects]]
  from = "/api/user/info"
  to = "/.netlify/functions/user-info"
  status = 200

[[redirects]]
  from = "/api/sync/subject/*"
  to = "/.netlify/functions/sync"
  status = 200

[[redirects]]
  from = "/api/sync"
  to = "/.netlify/functions/sync"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
